version: '3'

services:
  postgres:
    image: postgres:15
    container_name: DB-container
    restart: always
    networks: 
      - net-projet
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "2424:2424"

  backend:
    image: chetouiiftikhar/spring-img:${BUILD_ID}
    container_name: backend-container
    restart: always
    networks:
      - net-projet
    ports:
      - "8077:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://DB-container:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:  
  net-projet:
