version: '3'

services:
  postgres:
    image: postgres:15
    container_name: DB-container
    restart: always
    networks: 
      - net-projet
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "2424:2424"

  backend:
    image: chetouiiftikhar/spring-img:${BUILD_ID}
    container_name: backend-container
    restart: always
    networks:
      - net-projet
    ports:
      - "8077:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://DB-container:2424/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

networks:  
  net-projet:
